# Intersight provider init and configuration

terraform {
  required_providers {
    intersight = {
      source  = "CiscoDevNet/intersight"
      version = "0.1.1"
    }
  }
}

provider "intersight" {
  apikey        = data.vault_generic_secret.intersight_api_key.data.api_key
  secretkeyfile = var.secret_keyfile_name
  endpoint      = "https://intersight.com"
}

# Init Vault Provider 
# Vault will provide access to Consul
provider "vault" {
  address = var.vault_address
  token = var.vault_token
}

# Init Consul Provider 
# We access Consul using the secret generated by Vault
provider "consul" {
  address    = var.consul_address
  datacenter = var.consul_datacenter
  token = data.vault_generic_secret.consul.data.token
}